<?php

/**
 * This is example code for a Drupal 6 to Drupal 7 migration. This won't actually
 * work without defining the referenced vocabularies, content types, and fields
 * on each side.
 */

/**
 * Implements hook_flush_caches().
 */
function hr_migrate_flush_caches() {
  hr_migrate_register_migrations();
}

function hr_migrate_register_migrations() {
  hr_migrate_register_site_migration('www', 'www.humanitarianresponse.info');
  hr_migrate_register_site_migration('clusters', 'clusters.humanitarianresponse.info');
  hr_migrate_register_site_migration('imwg', 'imwg.humanitarianresponse.info');
}

/**
 * Register all D6->D7 migrations.
 */
function hr_migrate_register_site_migration($source_connection, $site) {
  $machine_name = '_' . $source_connection;
  if ($machine_name == '_www') {
    $machine_name = '';
  }
  /**
   * Each migration being registered takes an array of arguments, some required
   * and some optional. Start with the common arguments required by all - the
   * source_connection (connection key, set up in settings.php, pointing to
   * the Drupal 6 database), source_version (major version of Drupal), and
   * group_name (a.k.a. import job).
   */
  $common_arguments = array(
    'source_connection' => $source_connection,
    'source_version' => 7,
    'group_name' => 'hr',
  );

  // The description and the migration machine name are also required arguments,
  // which will be unique for each migration you register.
  $arguments = $common_arguments + array(
    'description' => t('Migration of users from '.$site),
    'machine_name' => 'hr_users'.$machine_name,
  );

  // We just use the migrate_d2d D6 migration class as-is.
  Migration::registerMigration('DrupalUser7Migration', $arguments['machine_name'],
                               $arguments);

  $profile_arguments = $common_arguments + array(
    'description' => t('Migration of user profiles from '.$site),
    'machine_name' => 'hr_profiles'.$machine_name,
    'user_migration' => 'hr_users'.$machine_name,
  );

  Migration::registerMigration('HRProfile2Migration', $profile_arguments['machine_name'], $profile_arguments);

  $fc_arguments = $common_arguments + array(
    'description' => t('Migration of field collections'),
    'machine_name' => 'hr_field_collections'.$machine_name,
  );

  Migration::registerMigration('HRFilesCollectionMigration', $fc_arguments['machine_name'], $fc_arguments);

  $files_arguments = $common_arguments + array(
    'description' => t('Migration of files'),
    'machine_name' => 'hr_files'.$machine_name,
    'user_migration' => 'hr_users'.$machine_name,
    'source_dir' => 'https://'.$site.'/sites/'.$site.'/files/',
    'site' => $site,
  );

  Migration::registerMigration('HRFileMigration', $files_arguments['machine_name'], $files_arguments);

  // Node migrations - each has its own class derived from the migrate_d2d class,
  // specifying its particular field mappings and transformations. source_type
  // and destination_type are required arguments.
  $node_arguments = array(
    array(
      'class_name' => 'HRPagesMigration',
      'description' => t('Migration of pages'),
      'machine_name' => 'hr_pages'.$machine_name,
      'source_type' => 'page',
      'destination_type' => 'hr_page',
    ),
    array(
      'class_name' => 'HRDocumentMigration',
      'description' => t('Migration of documents'),
      'machine_name' => 'hr_documents'.$machine_name,
      'source_type' => 'document',
      'destination_type' => 'hr_document',
    ),
    array(
      'class_name' => 'HRNewsMigration',
      'description' => t('Migration of news'),
      'machine_name' => 'hr_news'.$machine_name,
      'source_type' => 'news',
      'destination_type' => 'hr_news',
    ),
    array(
      'class_name' => 'HREventsMigration',
      'description' => t('Migration of events'),
      'machine_name' => 'hr_events'.$machine_name,
      'source_type' => 'event',
      'destination_type' => 'hr_event',
    ),
  );
  // Tell the node migrations where the users are coming from, so they can
  // set up the dependency and resolve D6->D7 uids.
  $common_node_arguments = $common_arguments + array(
    'user_migration' => 'hr_users'.$machine_name,
    'format_mappings' => array(
      'full_html' => 'panopoly_wysiwyg_text',
      'filtered_html' => 'panopoly_html_text',
      'simple' => 'panopoly_html_text',
      'plain_text' => 'plain_text',
    ),
  );
  foreach ($node_arguments as $arguments) {
    $arguments = array_merge_recursive($arguments, $common_node_arguments);
    Migration::registerMigration($arguments['class_name'], $arguments['machine_name'],
                                 $arguments);
  }

}

/**
 * Implements hook_migrate_api().
 */
function hr_migrate_migrate_api() {
  $api = array(
    'api' => 2,
    'groups' => array(
      'hr' => array(
        'title' => t('HR Migrations'),
      ),
    ),
  );
  return $api;
}
